# Generated by Django 3.1 on 2020-08-29 13:27

from django.db import migrations
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200829_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='user_pw',
            field=encrypted_fields.fields.EncryptedCharField(default=False, max_length=20),
        ),
    ]
