# Generated by Django 3.1 on 2020-08-30 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20200829_1335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loginuser',
            options={'verbose_name': 'user_Table'},
        ),
    ]
